site:
  title: Pioneer CDJ HID Analysis
  # url: https://djl-analysis.deepsymmetry.org
  start_page: hid-analysis::startup.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: docs
asciidoc:
  extensions:
  - asciidoctor-mathjax
plugins:
  - path: antora-generic-svg-extension-plugin
    config:
      generator: bytefield-svg
      name: bytefield
ui:
  bundle:
    url: https://deepsymmetry.org/media/antora/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"