# This is a basic workflow to help you get started with Actions

name: Build Doc

# Controls when the action will run. 
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Antora Site
        uses: jsqu4re/antora_build@0.1.1
